init:
  script:
    - echo "Start deployment..."

deploy:
  script:
    - echo "[DEPLOY] fab -f deploy-tools/fabfile.py deploy:host=ridwan@pmpl7ridwan-dev.cloudapp.net"
    - fab -f deploy-tools/fabfile.py deploy:host=ridwan@pmpl7ridwan-dev.cloudapp.net

test:
  script:
    - echo "[TEST] python3 manage.py test"
    - cd /home/ridwan/sites/pmpl7ridwan-dev.cloudapp.net/source
    - ../virtualenv/bin/python3 manage.py test
