init:
  script:
    - echo "Start deployment..."

deploy:
  script:
    - echo "[DEPLOY] fab -f deploy-tools/fabfile.py deploy:host=ridwan@pmpl7ridwan-dev.cloudapp.net"
    - fab -f deploy-tools/fabfile.py deploy:host=ridwan@pmpl7ridwan-dev.cloudapp.net
    - master

test:
  script:
    - echo "[TEST] python3 manage.py test"
    - /home/ridwan/sites/pmpl7ridwan-dev.cloudapp.net/virtualenv/bin/python3 manage.py test
    - master
